/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Test_H
#define Test_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "demo_types.h"

namespace demo {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TestIf {
 public:
  virtual ~TestIf() {}
  virtual void test() = 0;
  virtual void getStruct(std::string& _return, const int32_t key) = 0;
};

class TestIfFactory {
 public:
  typedef TestIf Handler;

  virtual ~TestIfFactory() {}

  virtual TestIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TestIf* /* handler */) = 0;
};

class TestIfSingletonFactory : virtual public TestIfFactory {
 public:
  TestIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TestIf>& iface) : iface_(iface) {}
  virtual ~TestIfSingletonFactory() {}

  virtual TestIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TestIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TestIf> iface_;
};

class TestNull : virtual public TestIf {
 public:
  virtual ~TestNull() {}
  void test() {
    return;
  }
  void getStruct(std::string& /* _return */, const int32_t /* key */) {
    return;
  }
};


class Test_test_args {
 public:

  Test_test_args(const Test_test_args&);
  Test_test_args& operator=(const Test_test_args&);
  Test_test_args() {
  }

  virtual ~Test_test_args() throw();

  bool operator == (const Test_test_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Test_test_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Test_test_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Test_test_pargs {
 public:


  virtual ~Test_test_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Test_test_result {
 public:

  Test_test_result(const Test_test_result&);
  Test_test_result& operator=(const Test_test_result&);
  Test_test_result() {
  }

  virtual ~Test_test_result() throw();

  bool operator == (const Test_test_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Test_test_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Test_test_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Test_test_presult {
 public:


  virtual ~Test_test_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Test_getStruct_args__isset {
  _Test_getStruct_args__isset() : key(false) {}
  bool key :1;
} _Test_getStruct_args__isset;

class Test_getStruct_args {
 public:

  Test_getStruct_args(const Test_getStruct_args&);
  Test_getStruct_args& operator=(const Test_getStruct_args&);
  Test_getStruct_args() : key(0) {
  }

  virtual ~Test_getStruct_args() throw();
  int32_t key;

  _Test_getStruct_args__isset __isset;

  void __set_key(const int32_t val);

  bool operator == (const Test_getStruct_args & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    return true;
  }
  bool operator != (const Test_getStruct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Test_getStruct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Test_getStruct_pargs {
 public:


  virtual ~Test_getStruct_pargs() throw();
  const int32_t* key;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Test_getStruct_result__isset {
  _Test_getStruct_result__isset() : success(false) {}
  bool success :1;
} _Test_getStruct_result__isset;

class Test_getStruct_result {
 public:

  Test_getStruct_result(const Test_getStruct_result&);
  Test_getStruct_result& operator=(const Test_getStruct_result&);
  Test_getStruct_result() : success() {
  }

  virtual ~Test_getStruct_result() throw();
  std::string success;

  _Test_getStruct_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Test_getStruct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Test_getStruct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Test_getStruct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Test_getStruct_presult__isset {
  _Test_getStruct_presult__isset() : success(false) {}
  bool success :1;
} _Test_getStruct_presult__isset;

class Test_getStruct_presult {
 public:


  virtual ~Test_getStruct_presult() throw();
  std::string* success;

  _Test_getStruct_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TestClient : virtual public TestIf {
 public:
  TestClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TestClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void test();
  void send_test();
  void recv_test();
  void getStruct(std::string& _return, const int32_t key);
  void send_getStruct(const int32_t key);
  void recv_getStruct(std::string& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TestProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TestIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TestProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_test(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getStruct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TestProcessor(::apache::thrift::stdcxx::shared_ptr<TestIf> iface) :
    iface_(iface) {
    processMap_["test"] = &TestProcessor::process_test;
    processMap_["getStruct"] = &TestProcessor::process_getStruct;
  }

  virtual ~TestProcessor() {}
};

class TestProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TestProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TestIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TestIfFactory > handlerFactory_;
};

class TestMultiface : virtual public TestIf {
 public:
  TestMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TestIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TestMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TestIf> > ifaces_;
  TestMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TestIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void test() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->test();
    }
    ifaces_[i]->test();
  }

  void getStruct(std::string& _return, const int32_t key) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getStruct(_return, key);
    }
    ifaces_[i]->getStruct(_return, key);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TestConcurrentClient : virtual public TestIf {
 public:
  TestConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TestConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void test();
  int32_t send_test();
  void recv_test(const int32_t seqid);
  void getStruct(std::string& _return, const int32_t key);
  int32_t send_getStruct(const int32_t key);
  void recv_getStruct(std::string& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
